CREATE TABLE IF NOT EXISTS employees (
	id SERIAL PRIMARY KEY,
	badgeid TEXT UNIQUE NOT NULL,
	name TEXT NOT NULL,
	department TEXT ,
	localname TEXT ,
	jobtitle TEXT 
);

CREATE TABLE IF NOT EXISTS departments (
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	code TEXT UNIQUE NOT NULL,
	manager_id INT UNIQUE REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	email TEXT UNIQUE,
	username TEXT UNIQUE NOT NULL,
	active BOOLEAN DEFAULT TRUE,
	otphash TEXT ,
	sessiontoken TEXT ,
	otpexpiry TIMESTAMP ,
	lastlogin TIMESTAMP ,
	incorrectotpattempts INTEGER ,
	online BOOLEAN DEFAULT FALSE,
	relatedemployee_id INT UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	description TEXT ,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
	id SERIAL PRIMARY KEY,
	resource TEXT UNIQUE NOT NULL,
	action TEXT UNIQUE NOT NULL,
	description TEXT ,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    _id INT REFERENCES s(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, _id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    _id INT REFERENCES s(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, _id)
);